# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  zookeeper0:
    container_name: zookeeper0
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    volumes:
      - /var/hyperledger/zk0/data:/data
      - /var/hyperledger/zk0/datalog:/datalog

  zookeeper1:
    container_name: zookeeper1
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    volumes:
      - /var/hyperledger/zk1/data:/data
      - /var/hyperledger/zk1/datalog:/datalog

  zookeeper2:
    container_name: zookeeper2
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    volumes:
      - /var/hyperledger/zk2/data:/data
      - /var/hyperledger/zk2/datalog:/datalog

  kafka0:
    container_name: kafka0
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - /var/hyperledger/kafka/kafka-logs0:/tmp/kafka-logs
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka1:
    container_name: kafka1
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - /var/hyperledger/kafka/kafka-logs1:/tmp/kafka-logs
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka2:
    container_name: kafka2
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - /var/hyperledger/kafka/kafka-logs2:/tmp/kafka-logs
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka3:
    container_name: kafka3
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - /var/hyperledger/kafka/kafka-logs3:/tmp/kafka-logs
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  orderer.wisedu.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.wisedu.com
    container_name: orderer.wisedu.com
    volumes:
      - /var/hyperledger/orderer:/var/hyperledger/production
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  peer0.org1.wisedu.com:
    container_name: peer0.org1.wisedu.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.wisedu.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
      - /var/hyperledger/peer0:/var/hyperledger/production
    depends_on:
      - couchdb1      

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    volumes:
      - /var/hyperledger/couchdb1:/opt/couchdb/data
    ports:
      - "6984:5984"

  peer1.org1.wisedu.com:
    container_name: peer1.org1.wisedu.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.wisedu.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
      - /var/hyperledger/peer1:/var/hyperledger/production
    depends_on:
      - couchdb2      

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb
    volumes:
      - /var/hyperledger/couchdb2:/opt/couchdb/data
    ports:
      - "7984:5984"

  peer0.org2.wisedu.com:
    container_name: peer0.org2.wisedu.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.wisedu.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
      - /var/hyperledger/peer2:/var/hyperledger/production
    depends_on:
      - couchdb3      

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb
    volumes:
      - /var/hyperledger/couchdb3:/opt/couchdb/data
    ports:
      - "8984:5984"

  peer1.org2.wisedu.com:
    container_name: peer1.org2.wisedu.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.wisedu.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb4:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
      - /var/hyperledger/peer3:/var/hyperledger/production
    depends_on:
      - couchdb4      

  couchdb4:
    container_name: couchdb4
    image: hyperledger/fabric-couchdb
    volumes:
      - /var/hyperledger/couchdb4:/opt/couchdb/data
    ports:
      - "9984:5984"

  peer0.org3.wisedu.com:
    container_name: peer0.org3.wisedu.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org3.wisedu.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb5:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
      - /var/hyperledger/peer4:/var/hyperledger/production
    depends_on:
      - couchdb5      

  couchdb5:
    container_name: couchdb5
    image: hyperledger/fabric-couchdb
    volumes:
      - /var/hyperledger/couchdb5:/opt/couchdb/data
    ports:
      - "10984:5984"

  peer1.org3.wisedu.com:
    container_name: peer1.org3.wisedu.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org3.wisedu.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb6:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    volumes:
      - /var/hyperledger/peer5:/var/hyperledger/production
    depends_on:
      - couchdb6      

  couchdb6:
    container_name: couchdb6
    image: hyperledger/fabric-couchdb
    volumes:
      - /var/hyperledger/couchdb6:/opt/couchdb/data
    ports:
      - "11984:5984"

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.wisedu.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wisedu.com/peers/peer0.org1.wisedu.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wisedu.com/peers/peer0.org1.wisedu.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wisedu.com/peers/peer0.org1.wisedu.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.wisedu.com/users/Admin@org1.wisedu.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
#    command: /bin/bash -c './scripts/script.sh ${CHANNEL_NAME}; sleep $TIMEOUT'
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/go/:/opt/gopath/src/github.com/hyperledger/fabric/examples/chaincode/go
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.wisedu.com
      - peer0.org1.wisedu.com
      - peer1.org1.wisedu.com
      - peer0.org2.wisedu.com
      - peer1.org2.wisedu.com
      - peer0.org3.wisedu.com
      - peer1.org3.wisedu.com
